<?php
  function gov_menu() {
    $items = array();
    $items['gov'] = array(
      'title' => 'Fed Taxes',
      'page callback' => 'get_gov',
      'access callback' => TRUE,
      'type' => MENU_NORMAL_ITEM,
    );

    return $items;
  }



  function get_gov(){
    $authorization = 'Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJBUElfS0VZX01BTkFHRVIiLCJodHRwOi8vdGF4ZWUuaW8vdXNlcl9pZCI6IjU5MTlmMTlmZTkyMWMwMzY2NjZmMTMxZiIsImh0dHA6Ly90YXhlZS5pby9zY29wZXMiOlsiYXBpIl0sImlhdCI6MTQ5NDg3MjQ3OX0.grP0a9fG_4NdaOaRWk5H-lwG9XOfcgic8eUmhTPF7Tc';
    $curl = curl_init();
    curl_setopt_array($curl, array(
      CURLOPT_RETURNTRANSFER => 1,
      CURLOPT_URL => 'https://taxee.io/api/v2/state/2017/OR',
      CURLOPT_USERAGENT => 'SeanCodes'
    ));
    // curl_setopt($curl, CURLOPT_HEADER, 1);
    curl_setopt($curl, CURLOPT_HTTPHEADER,array('Content-Type: application/json', $authorization));
    $articles = curl_exec($curl);
    curl_close($curl);
    $stuff = json_decode($articles, true);
    echo '<pre>';
    var_dump($stuff);
    echo '</pre>';

    return $stuff;
  }
