<?php
  function Take_Home_menu() {
    $items['Take_Home'] = array(
      'title' => "How much do you take home?",
      'page callback' => 'drupal_get_form',
      'page arguments' => array('Take_Home_form'),
      'access callback' => TRUE,
      'type' => MENU_NORMAL_ITEM,
    );

    $items['married'] = array(
      'page callback' => 'drupal_get_form',
      'page arguments' => array('married_form'),
      'access callback' => TRUE,
      'type' => MENU_CALLBACK,
    );
    $items['tax_bracket'] = array(
      'page callback' => 'drupal_get_form',
      'page arguments' => array('tax_bracket_form'),
      'access callback' => TRUE,
      'type' => MENU_CALLBACK,
    );
    $items['income'] = array(
      'page callback' => 'drupal_get_form',
      'page arguments' => array('income_form'),
      'access callback' => TRUE,
      'type' => MENU_CALLBACK,
    );
    $items['result'] = array(
      'title' => 'Your take home breakdown',
      'page callback' => 'results',
      'access callback' => TRUE,
      'type' => MENU_CALLBACK,
    );

    return $items;
  }

  function Take_Home_form() {
    unset($_SESSION['state_tax_rate']);
    $cities=db_query("SELECT * FROM col");
    $options=array();
    $states=array();
    foreach($cities as $value){
      $options[]=$value->city;
      $states[]=$value->state;
    }
    $_SESSION['unsorted_cities']=$options;
    $_SESSION['unsorted_states']=$states;
    sort($options);
    $_SESSION['cities']=$options;

    $form['cities'] = array(
      '#title' => "Which city do you live in?",
      '#type' => 'select',
      '#options' => $options,
      '#required' => TRUE,
    );

    $form['submit'] = array(
      '#type' => 'submit',
      '#value' => 'submit',
    );

    return $form;
  }
  function Take_Home_form_submit($form, &$form_state){
    $city = $form_state['values']['cities'];
    $_SESSION['city'] = $city;
    $form_state['redirect'] = 'income';
  }

  function income_form() {
    $form['income'] = array(
      '#title' => "What is your annual income?",
      '#type' => 'textfield',
      '#description' => 'no dollar signs or commas',
      '#required' => TRUE,
      '#element_validate' => array(
        'element_validate_integer_positive'
      ),

    );

    $form['submit'] = array(
      '#type' => 'submit',
      '#value' => 'submit',
    );

    return $form;
  }
  function income_form_submit($form, &$form_state){
    $income = $form_state['values']['income'];

    $_SESSION['income'] = $income;
    $form_state['redirect'] = 'married';
  }

  function married_form() {
    $form['married'] = array(
      '#title' => "Select your status",
      '#type' => 'radios',
      '#options' => array(t('Single'), t('Married')),
      '#required' => TRUE,
    );

      $form['submit'] = array(
        '#type' => 'submit',
        '#value' => 'submit',
      );

        return $form;
  }
  function married_form_submit($form, &$form_state){
    $relationship = $form_state['values']['married'];
    $_SESSION['relationship'] = $relationship;

    $city_number = $_SESSION['city'];
    $city=$_SESSION['cities'][$city_number];
    $key=array_search($city,$_SESSION['unsorted_cities']);
    $state=$_SESSION['unsorted_states'][$key];

    $_SESSION['user_city']=$city;
    $authorization = 'Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJBUElfS0VZX01BTkFHRVIiLCJodHRwOi8vdGF4ZWUuaW8vdXNlcl9pZCI6IjU5MTlmMTlmZTkyMWMwMzY2NjZmMTMxZiIsImh0dHA6Ly90YXhlZS5pby9zY29wZXMiOlsiYXBpIl0sImlhdCI6MTQ5NDg3MjQ3OX0.grP0a9fG_4NdaOaRWk5H-lwG9XOfcgic8eUmhTPF7Tc';
    $curl = curl_init();
    curl_setopt_array($curl, array(
      CURLOPT_RETURNTRANSFER => 1,
      CURLOPT_URL => 'https://taxee.io/api/v2/state/2017/'.$state,
      CURLOPT_USERAGENT => 'SeanCodes'
    ));

    curl_setopt($curl, CURLOPT_HTTPHEADER,array('Content-Type: application/json', $authorization));
    $articles = curl_exec($curl);
    curl_close($curl);
    $stuff = json_decode($articles, true);
    $relationship='';
    if($_SESSION['relationship'] == 0){
      $relationship='single';
    }else{
      $relationship='married';
    }
    if (isset($stuff[$relationship]['income_tax_brackets'])) {
      for($i=0;$i<count($stuff[$relationship]['income_tax_brackets']);$i++){
        if($_SESSION['income']<$stuff[$relationship]['income_tax_brackets'][$i]['bracket']){
            $tax_array_number=$i-1;
            break;
          }else{
            $tax_array_number=count($stuff[$relationship]['income_tax_brackets'])-1;
          }
      }

      $state_tax=(float)$stuff[$relationship]['income_tax_brackets'][$tax_array_number]['marginal_rate'];

      $_SESSION['state_tax_rate'] = $state_tax;
    }
    $form_state['redirect'] = 'result';
  }

  function results() {

    $relationship='';
    if($_SESSION['relationship'] == 0){
      $relationship='single';
    }else{
      $relationship='married';
    }

    $authorization = 'Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJBUElfS0VZX01BTkFHRVIiLCJodHRwOi8vdGF4ZWUuaW8vdXNlcl9pZCI6IjU5MTlmMTlmZTkyMWMwMzY2NjZmMTMxZiIsImh0dHA6Ly90YXhlZS5pby9zY29wZXMiOlsiYXBpIl0sImlhdCI6MTQ5NDg3MjQ3OX0.grP0a9fG_4NdaOaRWk5H-lwG9XOfcgic8eUmhTPF7Tc';
    $curl = curl_init();
    curl_setopt_array($curl, array(
      CURLOPT_RETURNTRANSFER => 1,
      CURLOPT_URL => 'https://taxee.io/api/v2/federal/2017',
      CURLOPT_USERAGENT => 'SeanCodes'
    ));
    curl_setopt($curl, CURLOPT_HTTPHEADER,array('Content-Type: application/json', $authorization));
    $articles = curl_exec($curl);
    curl_close($curl);
    $stuff = json_decode($articles, true);

    for($i=0;$i<count($stuff[$relationship]['income_tax_brackets']);$i++){
      if($_SESSION['income']<$stuff[$relationship]['income_tax_brackets'][$i]['bracket']){
          $tax_array_number=$i-1;
          break;
        }else{
          $tax_array_number=count($stuff[$relationship]['income_tax_brackets'])-1;
        }
    }

    $fed_tax=(float)$stuff[$relationship]['income_tax_brackets'][$tax_array_number]['marginal_rate'];
    $city=$_SESSION['user_city'];
    $cost=db_query("SELECT cost FROM col WHERE city = '{$city}'");
    $cost = $cost->fetchAssoc();
    $cost=(float)$cost['cost'];
    $rent=db_query("SELECT rent FROM col WHERE city = '{$city}'");
    $rent = $rent->fetchAssoc();
    $rent=(float)$rent['rent'];
    $NYcost=db_query("SELECT cost FROM col WHERE city = 'New York'");
    $NYcost = $NYcost->fetchAssoc();
    $NYcost=(float)$NYcost['cost'];
    $NYrent=db_query("SELECT rent FROM col WHERE city = 'New York'");
    $NYrent = $NYrent->fetchAssoc();
    $NYrent=(float)$NYrent['rent'];
    $col=$cost*$NYcost+$rent*$NYrent;
    $state_tax=0;
    if (isset($_SESSION['state_tax_rate'])) {
      $state_tax=$_SESSION['state_tax_rate'];
    }
    $take_home=$_SESSION['income']-($_SESSION['income']*($state_tax*.01))-($_SESSION['income']*($fed_tax*.01))-($col*12);

    $income=$_SESSION['income'];
    $state_tax_total=($_SESSION['income']*($state_tax*.01));
    $fed_tax_total=($_SESSION['income']*($fed_tax*.01));
    $annual_col=$col*12;
    $income_after_taxes=$income-$fed_tax_total-$state_tax_total;

    $user_city=$_SESSION['user_city'];
    return '<h1>Total Income: $'.$income.'</h1><hr><h3>Federal Income Tax: $'.$fed_tax_total.'</h3><h3>State Income Tax: $'.$state_tax_total.'</h3><h1>Income after taxes: $'.$income_after_taxes.'</h1><hr><h3>Average cost of living per month in '.$user_city.'(including 1bdrm rent in city): $'.(int)$col.'</h3><h3>Average cost of living per year in '.$user_city.'(including 1bdrm rent in city): $'.(int)$annual_col.'</h3><h3><a href=https://www.numbeo.com/cost-of-living/in/'.$user_city.'>cost of living source</a></h3><hr><h1>Monthly Take Home after taxes and cost of living: $'.(int)($take_home/12).'</h1><h1>Annual Take Home after taxes and cost of living: $'.(int)$take_home.'</h1>';
  }
